
DELETE http://localhost:5000/api/profile HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2ZjBmMTFjMzIxNGQ0M2M2ZTY4NDA4In0sImlhdCI6MTYwMTExMzg3MywiZXhwIjoxNjAxNDczODczfQ.Z5jYcEW_OAFr6QIiENpq4T_NgjxDzB518qq2K3gpNWU
###
DELETE http://localhost:5000/api/profile/experience/5f6f2cfb9475ef7a49c9b6ec HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2ZjBjMjU1ZTQ4MTIzY2ZlYWVhZWI3In0sImlhdCI6MTYwMTExMzIyNCwiZXhwIjoxNjAxNDczMjI0fQ.yLaceJuWk7cnlcp7vH4N7oSbkeLZZVTQiWCV6fV0exM
###

DELETE http://localhost:5000/api/profile/education/5f6f2e9a6ea7777e7d1137da HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2ZjBjMjU1ZTQ4MTIzY2ZlYWVhZWI3In0sImlhdCI6MTYwMTExMzIyNCwiZXhwIjoxNjAxNDczMjI0fQ.yLaceJuWk7cnlcp7vH4N7oSbkeLZZVTQiWCV6fV0exM
###
DELETE http://localhost:5000/api/posts/5f7038022772d3359692b85f HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2ZjBjMjU1ZTQ4MTIzY2ZlYWVhZWI3In0sImlhdCI6MTYwMTExMzIyNCwiZXhwIjoxNjAxNDczMjI0fQ.yLaceJuWk7cnlcp7vH4N7oSbkeLZZVTQiWCV6fV0exM
###
DELETE http://localhost:5000/api/posts/comment/5f703d6ee047c841401bb476/5f7045f06408e0597947a2ca HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY2ZjBjMjU1ZTQ4MTIzY2ZlYWVhZWI3In0sImlhdCI6MTYwMTExMzIyNCwiZXhwIjoxNjAxNDczMjI0fQ.yLaceJuWk7cnlcp7vH4N7oSbkeLZZVTQiWCV6fV0exM